name: Playwright UI Tests

on:
  push:
  pull_request:
  workflow_dispatch:  # 👈 Enables manual run via UI

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]   # Webkit removed OK

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Node (required for Playwright)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      # 🔹 Fix for your FIRST error (missing Linux dependencies)
      - name: Install Required Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwoff1 libvpx9 libevent-2.1-7t64 libopus0 \
          libgstreamer-plugins-base1.0-0 libgstreamer-gl1.0-0 libgstreamer-plugins-bad1.0-0 \
          libflite1 libavif16 libharfbuzz-icu0 libsecret-1-0 libhyphen0 \
          libmanette-0.2-0 libgles2 gstreamer1.0-libav

      - name: Install Playwright Browsers via Java
        run: mvn -q exec:java -Dexec.mainClass="setup.BrowserInstaller" || true

      - name: Run Playwright Tests
        run: |
          echo "Running on browser: ${{ matrix.browser }}"
          mvn -B test \
            -DBROWSER=${{ matrix.browser }} \
            -DHEADLESS=true \
            -Dsurefire.parallel=methods \
            -Dsurefire.threadCount=4

      - name: Upload Reports & Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ matrix.browser }}
          path: |
            reports/
            screenshots/