name: Playwright UI Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:                        # 🔥 Parallel browser execution
        browser: [chrome, firefox, webkit]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Node (required for Playwright internally)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-cache-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-cache-

      - name: Install Playwright Browsers
        run: mvn playwright:install

      - name: Run Playwright Tests 🚀
        run: |
          echo "Running tests on browser -> ${{ matrix.browser }}"
          mvn -B test \
            -DBROWSER=${{ matrix.browser }} \
            -DHEADLESS=true \
            -Dsurefire.parallel=methods \
            -Dsurefire.threadCount=4

      - name: Upload Reports & Screenshots 📁
        if: always()          # Upload even if tests fail!
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ matrix.browser }}
          path: |
            reports/
            screenshots/
